name:                category-theory-exercises
version:             0.1.0.0
github:              "koloc/category-theory-exercises"
license:             BSD3
author:              "Assen Kolov"
maintainer:          "assen.kolov@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/koloc/category-theory-exercises#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  category-theory-exercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-theory-exercises

tests:
  category-theory-exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-theory-exercises
